version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./pdfs:/app/pdfs
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: cloudflared tunnel --no-autoupdate --token ${CF_TUNNEL_TOKEN} certscraper.holocronlabs.net
    environment:
      - CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    depends_on:
      - app
    restart: unless-stopped